services:
  
  laravel-docker:
    container_name: insightify-web
    build: .
    volumes:
     - ./laravel-app:/var/www/html
    ports:
      - 9000:80
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - 9001:80
    environment:
     - PMA_ARBITRARY=1

    